export const getTypeImagePosition: Record<string, { backgroundPosition: string }> = {
  bug: { backgroundPosition: '0px 0px' },
  dark: { backgroundPosition: '-98px 0px' },
  dragon: { backgroundPosition: '-195px 0px' },
  electric: { backgroundPosition: '0px -49px' },
  fairy: { backgroundPosition: '-98px -49px' },
  fighting: { backgroundPosition: '-196px -49px' },
  fire: { backgroundPosition: '0px -99px' },
  flying: { backgroundPosition: '-98px -99px' },
  ghost: { backgroundPosition: '-196px -99px' },
  grass: { backgroundPosition: '0px -150px' },
  ground: { backgroundPosition: '-98px -150px' },
  ice: { backgroundPosition: '-195px -150px' },
  normal: { backgroundPosition: '0px -200px' },
  poison: { backgroundPosition: '-97px -200px' },
  psychic: { backgroundPosition: '-195px -200px' },
  rock: { backgroundPosition: '0px -250px' },
  steel: { backgroundPosition: '-97px -251px' },
  water: { backgroundPosition: '-195px -251px' }
}
